### ISSUE TITLE
赋予容器更高权限

### ISSUE THREAD

**Issue by lonelyevil** [gzycode39/docker-vapoursynth-yuuno#4]
避免形如 `set_mempolicy: Operation not permitted` 错误。参见鸭子群内带 numa 的 Xeon 事故。
为 `docker-compose.yml` 增加 `privileged: true`。
```
version: "2.1"
services:
    vapoursynth-yuuno:
...
        privileged: true
```
